index:
   path: /
   controller: App\Controller\ImportController::create

import_create:
  path:       /import/object
  controller: App\Controller\ImportController::create
  methods:    GET|POST

import_show:
  path:       /import/show
  controller: App\Controller\ImportController::show
  methods:    POST

import_help:
  path:       /import/help
  controller: App\Controller\HelpController::index
  methods:    GET

import_help_sample:
  path:       /import/help/sample
  controller: App\Controller\HelpController::sample
  methods:    GET
